server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=true
    username: spring
    password: spring
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  resources:
    static-locations: classpath:/templates/
  devtools:
    restart:
      enabled: true
jpa:
  hibernate:
  ddl-auto: update
  show-sql: true
test:
  myName: wulang
mybatis:
  mapper-locations: classpath:/mapper/*.Mapper.xml
  config-location: classpath:/mybatis/SqlMapConfig.xml
